services:
  - type: web
    name: all-tools
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app


---

## âš¡ Setup & Run Locally

1. **Clone the repository**

```bash
git clone https://github.com/Austine77/all_tools.git
cd all_tools
